image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cat "${CONFIG_PRIVATE_REGISTRY}" > ~/.yarnrc.yml
    - cat ~/.yarnrc.yml
    - yarn install --immutable
    - yarn test
    - yarn build
    - cd dist
    - touch yarn.lock
    - yarn install
    - yarn npm publish
  only:
    - main
  tags:
    - runner-cloud