export enum MerchantPresentedModeCodes {
  ID_PAYLOAD_FORMAT_INDICATOR = '00',
  ID_POINT_OF_INITIATION_METHOD = '01',
  ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_RANGE_START = '02',
  ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_RANGE_END = '25',
  ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_ADDITIONAL_RANGE_START = '26',
  ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_ADDITIONAL_RANGE_END = '51',
  ID_MERCHANT_CATEGORY_CODE = '52',
  ID_TRANSACTION_CURRENCY = '53',
  ID_TRANSACTION_AMOUNT = '54',
  ID_TIP_OR_CONVENIENCE_INDICATOR = '55',
  ID_VALUE_OF_CONVENIENCE_FEE_FIXED = '56',
  ID_VALUE_OF_CONVENIENCE_FEE_PERCENTAGE = '57',
  ID_COUNTRY_CODE = '58',
  ID_MERCHANT_NAME = '59',
  ID_MERCHANT_CITY = '60',
  ID_POSTAL_CODE = '61',
  ID_ADDITIONAL_DATA_FIELD_TEMPLATE = '62',
  ID_CRC = '63',
  ID_MERCHANT_INFORMATION_LANGUAGE_TEMPLATE = '64',
  ID_RFU_FOR_EMVCO_RANGE_START = '65',
  ID_RFU_FOR_EMVCO_RANGE_END = '79',
  ID_UNRESERVED_TEMPLATES_RANGE_START = '80',
  ID_UNRESERVED_TEMPLATES_RANGE_END = '99',

  ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED = ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_RANGE_START,
  ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_ADDITIONAL = ID_MERCHANT_ACCOUNT_INFORMATION_RESERVED_ADDITIONAL_RANGE_START,
  ID_RFU_FOR_EMVCO = ID_RFU_FOR_EMVCO_RANGE_START,
  ID_UNRESERVED_TEMPLATES = ID_UNRESERVED_TEMPLATES_RANGE_START,
}

export enum MerchantAccountInformationFieldCodes {
  ID_GLOBALLY_UNIQUE_IDENTIFIER = '00',
  ID_PAYMENT_NETWORK_SPECIFIC_START = '01',
  ID_PAYMENT_NETWORK_SPECIFIC_END = '99',
  ID_PAYMENT_NETWORK_SPECIFIC = ID_PAYMENT_NETWORK_SPECIFIC_START,
}

export enum MerchantInformationLanguageFieldCodes {
  ID_LANGUAGE_PREFERENCE = '00',
  ID_MERCHANT_NAME = '01',
  ID_MERCHANT_CITY = '02',
  ID_RFU_FOR_EMVCO_RANGE_START = '03',
  ID_RFU_FOR_EMVCO_RANGE_END = '99',
  ID_RFU_FOR_EMVCO = ID_RFU_FOR_EMVCO_RANGE_START,
}

export enum AdditionalDataFieldCodes {
  ID_BILL_NUMBER = '01',
  ID_MOBILE_NUMBER = '02',
  ID_STORE_LABEL = '03',
  ID_LOYALTY_NUMBER = '04',
  ID_REFERENCE_LABEL = '05',
  ID_CUSTOMER_LABEL = '06',
  ID_TERMINAL_LABEL = '07',
  ID_PURPOSE_TRANSACTION = '08',
  ID_ADDITIONAL_CONSUMER_DATA_REQUEST = '09',
  ID_RFU_FOR_EMVCO_RANGE_START = '10',
  ID_RFU_FOR_EMVCO_RANGE_END = '49',
  ID_PAYMENT_SYSTEM_SPECIFIC_TEMPLATES_RANGE_START = '50',
  ID_PAYMENT_SYSTEM_SPECIFIC_TEMPLATES_RANGE_END = '99',
  ID_RFU_FOR_EMVCO = ID_RFU_FOR_EMVCO_RANGE_START,
  ID_PAYMENT_SYSTEM_SPECIFIC = ID_PAYMENT_SYSTEM_SPECIFIC_TEMPLATES_RANGE_START,
}

export enum UnreservedTemplateFieldCodes {

  ID_GLOBALLY_UNIQUE_IDENTIFIER = "00",
  ID_CONTEXT_SPECIFIC_DATA_START = "01",
  ID_CONTEXT_SPECIFIC_DATA_END = "99", 

  // Reserved
  ID_CONTEXT_SPECIFIC_DATA = ID_CONTEXT_SPECIFIC_DATA_START,

}

export enum PointOfInitiationMethod {
  STATIC = "11",
  DYNAMIC = "12"
}